In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import datetime

In [2]:
df = pd.read_json('data/data.json')

In [3]:
df.T

0      \
acct_type                                             fraudster_event   
approx_payout_date                                         1266062400   
body_length                                                      3852   
channels                                                            5   
country                                                            US   
currency                                                          USD   
delivery_method                                                   0.0   
description         <p><a href="http://s432.photobucket.com/albums...   
email_domain                                                gmail.com   
event_created                                              1262739706   
event_end                                                  1265630400   
event_published                                          1263109838.0   
event_start                                                1265594400   
fb_published                                                        0   
gts                                                               0.0   
has_analytics                                                       0   
has_header                                                        1.0   
has_logo                                                            0   
listed                                                              y   
name                99 HOUR "NO SLEEP" SUPER BOWL CELEBRITY WEEKEN...   
name_length                                                        60   
num_order                                                           0   
num_payouts                                                         0   
object_id                                                      527017   
org_desc                                                                
org_facebook                                                      0.0   
org_name                        Party Starz Ent & Diverse Int'l Group   
org_twitter                                                       0.0   
payee_name                                                              
payout_type                                                             
previous_payouts                                                   []   
sale_duration                                                    29.0   
sale_duration2                                                     33   
show_map                                                            1   
ticket_types        [{'event_id': 527017, 'cost': 25.0, 'availabil...   
user_age                                                           36   
user_created                                               1259613950   
user_type                                                           1   
venue_address                                   717 Washington Avenue   
venue_country                                                      US   
venue_latitude                                              25.777471   
venue_longitude                                            -80.133433   
venue_name                                INK Nightclub - South Beach   
venue_state                                                        FL   

                                                                1      \
acct_type                                                     premium   
approx_payout_date                                         1296720000   
body_length                                                      3499   
channels                                                            0   
country                                                            US   
currency                                                          USD   
delivery_method                                                   1.0   
description         <p>Join us for a quick, one-night, community-b...   
email_domain                                                  ruf.org   
event_created                                   

### Previous Payouts Explore

In [4]:
len(df.loc[1, 'previous_payouts'])

49

In [5]:
df['previous_payouts'].apply(lambda x: len(x))

0          0
1         49
2         36
3         21
4         49
        ... 
14332      0
14333      5
14334      1
14335    128
14336      0
Name: previous_payouts, Length: 14337, dtype: int64

In [6]:
df['n_payouts'] = df['previous_payouts'].apply(lambda x: len(x))

In [7]:
df.loc[1, 'previous_payouts'][0]['uid']

5419068

In [8]:
np.unique([payee['uid'] for payee in df.loc[1, 'previous_payouts']])

array([5419068])

In [9]:
datetime.datetime.fromtimestamp(df.loc[2, 'approx_payout_date'])

datetime.datetime(2011, 1, 27, 16, 0)

In [10]:
# Make fraud column 
df['fraud'] = df.acct_type.apply(lambda x: 1 if 'fraud' in x else 0)

# Get columns 
columns = list(df.columns)

## Model

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [15]:
df

acct_type  approx_payout_date  body_length  channels country  \
0      fraudster_event          1266062400         3852         5      US   
1              premium          1296720000         3499         0      US   
2              premium          1296172800         2601         8      US   
3              premium          1388966400        12347         6      IE   
4              premium          1297900800         2417        11      US   
...                ...                 ...          ...       ...     ...   
14332  fraudster_event          1361689200          667         0      US   
14333          premium          1365566400         5812         5      US   
14334          premium          1368781200          557        13           
14335         tos_warn          1361361600        10873         8      US   
14336  fraudster_event          1363316400            0         0      GB   

      currency  delivery_method  \
0          USD              0.0   
1          USD              1.0   
2          USD              1.0   
3          EUR              1.0   
4          USD              0.0   
...        ...              ...   
14332      USD              0.0   
14333      USD              1.0   
14334      USD              0.0   
14335      USD              0.0   
14336      GBP              0.0   

                                             description  \
0      <p><a href="http://s432.photobucket.com/albums...   
1      <p>Join us for a quick, one-night, community-b...   
2      <h3><span class="subcategory"><strong>Teacher ...   
3      <p style="margin-bottom: 1.3em; padding-bottom...   
4      <p>Writers and filmmakers need to understand t...   
...                                                  ...   
14332  <p>Celebrates this wonderful holiday with the ...   
14333  <table style="width: 600px;" border="0" cellsp...   
14334  <p>What a way to start off your Mother's Day l...   
14335  <p style="font-family: 'Helvetica Neue', Helve...   
14336                                                      

                     email_domain  event_created  ...  user_created  \
0                       gmail.com     1262739706  ...    1259613950   
1                         ruf.org     1293832670  ...    1280942776   
2                  pvsd.k12.ca.us     1291090956  ...    1272559388   
3            irishtabletennis.com     1360681570  ...    1283870102   
4      artsandbusinesscouncil.org     1291994666  ...    1288984065   
...                           ...            ...  ...           ...   
14332                   yahoo.com     1360297993  ...    1360297993   
14333                      me.com     1360367042  ...    1241625346   
14334                   yahoo.com     1360600330  ...    1353386971   
14335              velvetlist.com     1360376285  ...    1290204991   
14336                   gmail.com     1360686846  ...    1360686845   

       user_type                 venue_address  venue_country  venue_latitude  \
0              1         717 Washington Avenue             US       25.777471   
1              3                                           US       32.776566   
2              3  10100 Pioneer Blvd Suite 100             US       33.944201   
3              3                                         None             NaN   
4              3        One Marina Park Drive              US       42.353848   
...          ...                           ...            ...             ...   
14332          1     6100 North Charles Street             US       39.373780   
14333          4         1775 E Mission Bay Dr             US       32.778906   
14334          4             5991 Bullard Road             US       30.041819   
14335          3               2297 Cedar Ave              US       40.862283   
14336          1           192 Pembroke Street             GB       51.460131   

       venue_longitude                                         venue_name  \
0           -80.133433                     

In [16]:
mask = df.previous_payouts.apply(lambda x: 0 if len(x) <= 0 else 1)
df['mask_previous_payout'] = mask
X = df[['mask_previous_payout', 'user_age']]
y = df['fraud']

In [17]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y)
model = LogisticRegression()
model.fit(Xtrain, ytrain)

LogisticRegression()

In [18]:
model.predict(Xtest)

array([0, 0, 0, ..., 0, 0, 0])

In [58]:
import pickle

In [62]:
model_path = "model.pickle"

In [64]:
pickle.dump(model, open(model_path, 'wb'))

In [65]:
new_model = pickle.load(open(model_path, 'rb'))

In [66]:
new_model.predict_proba(Xtest)

array([[0.96513266, 0.03486734],
       [0.96502979, 0.03497021],
       [0.96513266, 0.03486734],
       ...,
       [0.96502979, 0.03497021],
       [0.98256968, 0.01743032],
       [0.96559197, 0.03440803]])

In [135]:
model2 = pickle.load(open('models/model.pickle', 'rb'))

/Users/vinsonmccready/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.23.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


In [138]:
model2.predict_proba(Xtest)

array([[0.03549236, 0.96450764],
       [0.03561665, 0.96438335],
       [0.03549236, 0.96450764],
       ...,
       [0.03561665, 0.96438335],
       [0.01556803, 0.98443197],
       [0.03493821, 0.96506179]])

In [31]:
import requests

In [42]:
from src.api_client import EventAPIClient

In [94]:
data_path = 'data/api_data.json'

In [95]:
pd.DataFrame([pd.Series(data['data'][0])]).to_json(data_path)

In [96]:
df2 = pd.read_json(data_path)

In [103]:
def get_X(df):
    mask = df.previous_payouts.apply(lambda x: 0 if len(x) <= 0 else 1)
    df['mask_previous_payout'] = mask
    X = df[['mask_previous_payout', 'user_age']]
    return X

In [104]:
new_model.predict_proba(X2)

array([[0.98380536, 0.01619464]])

In [151]:
data['data'][0]

{'body_length': 2267,
 'channels': 8,
 'country': 'CA',
 'currency': 'CAD',
 'delivery_method': 1.0,
 'description': '<p><span style="font-size: large;">This registration encompasses:</span></p>\r\n<ul>\r\n<li><span style="font-size: large;">Attendance or access to the recordings of the three free Hosted Conversations (April, May and June 2013)</span></li>\r\n<li><span style="font-size: large;">3 tele-classes (Sept. 19th, Oct. 3rd and Oct. 17th 2013)</span></li>\r\n<li><span style="font-size: large;">Tuition, room and board* at the 6-day retreat Nov. 11th through 17th, 2013.</span></li>\r\n</ul>\r\n<p><font size="4">* Double occupancy</font></p>\r\n<p><span style="font-size: large; font-family: arial, helvetica, sans-serif;"><br /></span></p>\r\n<p><span style="font-size: large; font-family: arial, helvetica, sans-serif;">For information about the full Program:<br /></span></p>\r\n<div style="text-align: -webkit-auto;"><span style="font-family: arial, helvetica, sans-serif; font-size: 

In [19]:
import pymongo
import time
import requests

In [20]:
db_client = pymongo.MongoClient('localhost', 27017)
db = db_client['fraud']
cases = db.cases

In [150]:
cases.insert_one(data['data'][0])

DuplicateKeyError: E11000 duplicate key error collection: fraud.cases index: _id_ dup key: { _id: ObjectId('6078caa268e6c0707967bc68') }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('6078caa268e6c0707967bc68')}, 'errmsg': "E11000 duplicate key error collection: fraud.cases index: _id_ dup key: { _id: ObjectId('6078caa268e6c0707967bc68') }"}

In [29]:
first_sequence_number=0
next_sequence_number = first_sequence_number

In [32]:

api_url='https://hxobin8em5.execute-api.us-west-2.amazonaws.com/api/'
api_key='vYm9mTUuspeyAWH1v-acfoTlck-tCxwTw9YfCynC'


def get_data(next_sequence_number):
    """Fetch data from the API."""
    payload = {'api_key': api_key,
               'sequence_number': next_sequence_number}
    response = requests.post(api_url, json=payload)
    data = response.json()
    next_sequence_number = data['_next_sequence_number']
    return data['data']

interval=30
while True:
    print("Requesting data...")
    data = get_data(next_sequence_number)
    if data:
        print("Saving...")
        for row in data:
            cases.insert_one(row)
    else:
        print("No new data received.")
    print(f"Waiting {interval} seconds...")
    time.sleep(interval)

Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Waiting 30 seconds...
Requesting data...
Saving...
Wa

ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

In [39]:
api_data = pd.DataFrame(list(cases.find())).drop_duplicates('object_id').reset_index()

In [42]:
api_data = api_data.drop(['_id', 'index'], axis=1)

In [43]:
api_data.to_json('data/api_data.json')

In [44]:
api_df =  pd.read_json('data/api_data.json') 

In [45]:
api_df

body_length  channels country currency  delivery_method  \
0          2267         8      CA      CAD                1   
1          3109         6      US      USD                0   
2          3107        12      US      USD                0   
3         15036         8              CAD                0   
4          2010         8      US      USD                0   
5          3702         8      US      USD                0   
6          1403         6      US      USD                1   
7          3215         8      GB      GBP                0   
8           608         5      US      USD                0   
9          3172        11      CA      CAD                0   
10        13329        11      US      USD                1   
11         3513         8      GB      GBP                0   
12         3706         8      US      USD                1   
13         2244         5      US      USD                0   
14         1463        11      CA      CAD                1   
15         6953         5      CA      CAD                1   
16         1395         6      US      USD                0   
17          273         0      US      USD                1   

                                          description  \
0   <p><span style="font-size: large;">This regist...   
1   <p style="text-align: justify;"><span style="c...   
2   <p><span style="font-size: x-large;"><span sty...   
3   <p style="font-family: 'Helvetica Neue', Helve...   
4   <p style="color: #000000;"><font face="georgia...   
5   <p><img style="float: right;"  alt="Mobile Mar...   
6   <p><font size="3">Vogue Magazine, Style 360, a...   
7   <p style="margin: 0px; padding: 0px 0px 8px; f...   
8   <div></div>\r\n<div style="text-align: center;...   
9   <div class="mbl notesBlogText clearfix">\r\n<d...   
10  <p> </p>\r\n<p style="text-align: center;"><im...   
11  <p><span style="font-family: Arial,sans-serif;...   
12  <p style="text-align: center;"><strong><font s...   
13  <p>Elephant Revival, neo-acoustic transcendent...   
14  <p>This introductory session will examine what...   
15  <p><span style="font-family: tahoma,arial,helv...   
16  <p><font size="6" face="arial, helvetica, sans...   
17  <p>YOU MUST HAVE ATTENDED THE OCTOBER ORIENTAT...   

               email_domain  event_created   event_end  event_published  ...  \
0               spiralis.ca     1359490099  1366516800       1359490251  ...   
1                 yahoo.com     1365689629  1366522200       1365699150  ...   
2                 yahoo.com     1365890353  1369976400       1365890402  ...   
3               hotmail.com     1365893145  1369369800       1365894159  ...   
4          generalassemb.ly     1308696562  1309919400       1308864868  ...   
5             mmaglobal.com     1308709465  1312414200       1309361486  ...   
6                 gmail.com     1309145477  1311404400       1309147698  ...   
7        breakwaterfp.co.uk     1346415992  1348781400       1346427157  ...   
8              nycap.rr.com     1309450850  1312693200       1309451593  ...   
9             kortaggio.com     1310311965  1319934600       1312302797  ...   
10                genpa.org     1310321793  1320534000       1311187289  ...   
11         jcilondon.org.uk     1310589774  1313121600       1310590920  ...   
12            marklogic.com     1311953620  1316736000       1312392642  ...   
13                gmail.com     1312421486  1317970500       1312421714  ...   
14  unitedwaywinnipeg.mb.ca     1313076456  1321471800       1313077316  ...   
15      powerstartgroup.com     1313076887  1322724600       1313076965  ...   
16          savannahnow.com     1313077417  1329094800       1313437635  ...   
17                 ddfl.org     1317328569  1319864400       1317478713  ...   

    user_age  user_created  user_type            venue_address  venue_country  \
0        517    1314799174          3   Ecology Retreat Center             CA   
1        371    1333660943          4  

In [120]:
def not_premium(x):
    return 1 if x.lower() != 'premium' else 0

def no_previous_payout(x):
    return 1 if len(x) <= 0 else 0

def payout_name_flag(x):
    for d in x:
        if len(d['name']) > 3:
            return 1
    return 0

def payout_toself(payee, payouts):
    for pay in payouts:
        if payee.lower() in pay['name'].lower():
            return 1
    return 0

# ---------------------------------------------------------------------------
# End Pipeline Funtions 
# ---------------------------------------------------------------------------
def data_pipeline(df):
    temp = dict()
    temp = {
#         'target': df['fraud'].copy(), 
#             'premium': df.acct_type.apply(lambda x: not_premium(x)),
            'previous_payout': df.previous_payouts.apply(lambda x: no_previous_payout(x)),
            'no_payout_name': df.previous_payouts.apply(lambda x: payout_name_flag(x)),
            'payout_toself': df.apply(lambda x: payout_toself(x.payee_name, x.previous_payouts), axis = 1)
        }
        
    return pd.DataFrame(temp)

In [121]:
data_pipeline(pd.DataFrame([pd.Series(data['data'][0])]))

previous_payout  no_payout_name  payout_toself
0                0               0              1

In [145]:
for c in pd.DataFrame([pd.Series(data['data'][0])]).columns:
    print(c)

body_length
channels
country
currency
delivery_method
description
email_domain
event_created
event_end
event_published
event_start
fb_published
has_analytics
has_header
has_logo
listed
name
name_length
object_id
org_desc
org_facebook
org_name
org_twitter
payee_name
payout_type
previous_payouts
sale_duration
show_map
ticket_types
user_age
user_created
user_type
venue_address
venue_country
venue_latitude
venue_longitude
venue_name
venue_state
sequence_number


In [119]:
pd.DataFrame([pd.Series(data['data'][0])])['description'].values[0]

'<p><span style="font-size: large;">This registration encompasses:</span></p>\r\n<ul>\r\n<li><span style="font-size: large;">Attendance or access to the recordings of the three free Hosted Conversations (April, May and June 2013)</span></li>\r\n<li><span style="font-size: large;">3 tele-classes (Sept. 19th, Oct. 3rd and Oct. 17th 2013)</span></li>\r\n<li><span style="font-size: large;">Tuition, room and board* at the 6-day retreat Nov. 11th through 17th, 2013.</span></li>\r\n</ul>\r\n<p><font size="4">* Double occupancy</font></p>\r\n<p><span style="font-size: large; font-family: arial, helvetica, sans-serif;"><br /></span></p>\r\n<p><span style="font-size: large; font-family: arial, helvetica, sans-serif;">For information about the full Program:<br /></span></p>\r\n<div style="text-align: -webkit-auto;"><span style="font-family: arial, helvetica, sans-serif; font-size: large;"><font color="#666666" face="sans-serif"><span style="line-height: 16px;">trainingnvctrainers.com</span></font